# questions.py
# Savollar bazasi: 0 dan PRO gacha, 8 bo'lim + ⛩ anime lug'ati.
# Yangi savol qo'shish uchun kerakli ro'yxatga yangi dict qo'shing.

CATEGORIES = {
    "lugat_a1": "📖 Lug'at — A1",
    "lugat_a2": "📚 Lug'at — A2–B1",
    "gram_a1": "📘 Grammatika — A1",
    "gram_b": "📗 Grammatika — A2–B2",
    "talaffuz": "🗣 Talaffuz",
    "suhbat": "💬 Jonli so'zlashuv",
    "dialog": "🗨 Real muloqot (PRO)",
    "anime": "⛩ Anime tili (test)",
}

QUESTIONS = {
    "lugat_a1": [
        {"savol": "«Молоко» so'zining ma'nosi nima?", "variantlar": ["Suv", "Sut", "Non", "Choy"], "togri": 1, "izoh": "Молоко — sut. Talaffuzi: «malako»."},
        {"savol": "«Книга» so'zining ma'nosi nima?", "variantlar": ["Deraza", "Stol", "Kitob", "Eshik"], "togri": 2, "izoh": "Книга — kitob. Urg'u: КНИ́-га."},
        {"savol": "«Окно» so'zining ma'nosi nima?", "variantlar": ["Deraza", "Devor", "Shift", "Pol"], "togri": 0, "izoh": "Окно — deraza. Urg'u oxirida: «akno»."},
        {"savol": "«Вода» so'zining ma'nosi nima?", "variantlar": ["Suv", "Olov", "Havo", "Tuproq"], "togri": 0, "izoh": "Вода — suv. Talaffuzi: «vada»."},
        {"savol": "«Друг» so'zining ma'nosi nima?", "variantlar": ["Dushman", "Qo'shni", "Do'st", "Aka"], "togri": 2, "izoh": "Друг — do'st. Talaffuzi: «druk»."},
        {"savol": "«Хлеб» so'zining ma'nosi nima?", "variantlar": ["Non", "Suv", "Go'sht", "Tuz"], "togri": 0, "izoh": "Хлеб — non. Talaffuzi: «xlep»."},
        {"savol": "«Дом» so'zining ma'nosi nima?", "variantlar": ["Uy", "Ko'cha", "Shahar", "Xona"], "togri": 0, "izoh": "Дом — uy. Я дома — Men uydaman."},
        {"savol": "«Кошка» so'zining ma'nosi nima?", "variantlar": ["It", "Mushuk", "Qush", "Sigir"], "togri": 1, "izoh": "Кошка — mushuk. It esa — собака."},
        {"savol": "«Семья» so'zining ma'nosi nima?", "variantlar": ["Do'stlar", "Oila", "Qo'shnilar", "Bolalar"], "togri": 1, "izoh": "Семья — oila. Talaffuzi: «sim'ya»."},
        {"savol": "«Rahmat» ruschada qanday aytiladi?", "variantlar": ["Пожалуйста", "Спасибо", "Привет", "Пока"], "togri": 1, "izoh": "Спасибо — rahmat. Javobi: Пожалуйста (arzimaydi)."},
    ],
    "lugat_a2": [
        {"savol": "«Путешествие» so'zining ma'nosi nima?", "variantlar": ["Sayohat", "Uchrashuv", "Bayram", "Dam olish"], "togri": 0, "izoh": "Путешествие — sayohat. Путь — yo'l so'zidan."},
        {"savol": "«Здоровье» so'zining ma'nosi nima?", "variantlar": ["Baxt", "Salomatlik", "Boylik", "Kuch"], "togri": 1, "izoh": "Здоровье — salomatlik. Здоровый — sog'lom."},
        {"savol": "«Мечта» so'zining ma'nosi nima?", "variantlar": ["Xotira", "Orzu", "Reja", "Maqsad"], "togri": 1, "izoh": "Мечта — orzu. Мечтать — orzu qilmoq."},
        {"savol": "«Успех» so'zining ma'nosi nima?", "variantlar": ["Omad", "Muvaffaqiyat", "G'alaba", "Baxt"], "togri": 1, "izoh": "Успех — muvaffaqiyat. Успешный — muvaffaqiyatli."},
        {"savol": "«Опаздывать» fe'lining ma'nosi nima?", "variantlar": ["Shoshilmoq", "Kechikmoq", "Kutmoq", "Yugurmoq"], "togri": 1, "izoh": "Опаздывать — kechikmoq. Я опаздываю — kechikyapman."},
        {"savol": "«Удивляться» fe'lining ma'nosi nima?", "variantlar": ["Xafa bo'lmoq", "Hayron qolmoq", "Quvonmoq", "Qo'rqmoq"], "togri": 1, "izoh": "Удивляться — hayron qolmoq. -ся — o'zlik qo'shimchasi."},
        {"savol": "«Приходить» fe'lining ma'nosi nima?", "variantlar": ["Ketmoq", "Kelmoq", "Qolmoq", "Chiqmoq"], "togri": 1, "izoh": "При- old qo'shimchasi yaqinlashishni bildiradi: приходить — kelmoq."},
        {"savol": "«Вспоминать» fe'lining ma'nosi nima?", "variantlar": ["Unutmoq", "Eslamoq", "O'ylamoq", "Bilmoq"], "togri": 1, "izoh": "Вспоминать — eslamoq. Unutmoq esa — забывать."},
    ],
    "gram_a1": [
        {"savol": "Rus tilida nechta jins (род) bor?", "variantlar": ["2 ta", "3 ta", "4 ta", "Jins yo'q"], "togri": 1, "izoh": "3 ta: мужской (erkak), женский (ayol), средний (o'rta)."},
        {"savol": "«Книга» so'zi qaysi jinsda?", "variantlar": ["Мужской", "Женский", "Средний", "Jinsi yo'q"], "togri": 1, "izoh": "-а bilan tugagan so'zlar odatda женский род: книга, вода, школа."},
        {"savol": "«Окно» so'zi qaysi jinsda?", "variantlar": ["Мужской", "Женский", "Средний", "Ko'plik"], "togri": 2, "izoh": "-о/-е bilan tugagan so'zlar средний род: окно, молоко, море."},
        {"savol": "«Я студент» gapining to'g'ri tarjimasi qaysi?", "variantlar": ["Men talabaman", "U talaba", "Men talaba edim", "Men talaba bo'laman"], "togri": 0, "izoh": "Hozirgi zamonda «быть» tushib qoladi: Я студент = Men talabaman."},
        {"savol": "«Вы» qachon ishlatiladi?", "variantlar": ["Faqat ko'plikda", "Hurmat va rasmiylikda (hamda ko'plikda)", "Faqat do'stlarga", "Faqat bolalarga"], "togri": 1, "izoh": "Вы — «siz»: notanish/katta odamlarga va ko'plikda. Ты — yaqinlarga."},
        {"savol": "«Книга» so'zining ko'pligi qaysi?", "variantlar": ["Книгы", "Книги", "Книгов", "Книгалар"], "togri": 1, "izoh": "г, к, х dan keyin ы emas, и yoziladi: книга → книги."},
        {"savol": "«Mening kitobim» ruschada qanday?", "variantlar": ["Мой книга", "Моя книга", "Моё книга", "Мои книга"], "togri": 1, "izoh": "Книга — женский род, shuning uchun моя: моя книга."},
        {"savol": "«Молоко» o'rniga qaysi olmosh qo'yiladi?", "variantlar": ["Он", "Она", "Оно", "Они"], "togri": 2, "izoh": "Средний род so'zlar — оно: молоко → оно."},
    ],
    "gram_b": [
        {"savol": "Rus tilida nechta kelishik bor?", "variantlar": ["4 ta", "5 ta", "6 ta", "7 ta"], "togri": 2, "izoh": "6 ta: именительный, родительный, дательный, винительный, творительный, предложный."},
        {"savol": "«Я читаю книгу» gapida «книгу» qaysi kelishikda?", "variantlar": ["Именительный", "Родительный", "Винительный", "Дательный"], "togri": 2, "izoh": "Винительный (tushum): книга → книгу (-а → -у)."},
        {"savol": "«Говорить» fe'li qaysi tuslanishga kiradi?", "variantlar": ["1-tuslanish", "2-tuslanish", "Noto'g'ri fe'l", "Tuslanmaydi"], "togri": 1, "izoh": "-ить fe'llari 2-tuslanish: я говорю, ты говоришь."},
        {"savol": "«Читать» va «прочитать» farqi nimada?", "variantlar": ["Zamon farqi", "Davomiy va tugallangan ish (вид)", "Jins farqi", "Farqi yo'q"], "togri": 1, "izoh": "Читать — jarayon (o'qib turish), прочитать — tugallangan (o'qib bo'lish). Bu — вид (aspekt)."},
        {"savol": "«У меня есть кот» gapining ma'nosi nima?", "variantlar": ["Men mushukman", "Menda mushuk bor", "Mushukni ko'rdim", "Mushuk yo'q"], "togri": 1, "izoh": "У меня есть... — «Menda ... bor» konstruksiyasi."},
        {"savol": "«Идти» va «ходить» farqi nimada?", "variantlar": ["Farqi yo'q", "Идти — hozir bir yo'nalishda, ходить — takroriy", "Идти — yugurish", "Ходить — faqat o'tgan zamon"], "togri": 1, "izoh": "Идти — hozir bir tomonga ketyapman; ходить — doim/takror boraman (harakat fe'llari)."},
        {"savol": "O'tgan zamonda ayol jinsida fe'l qanday tugaydi?", "variantlar": ["-л", "-ла", "-ло", "-ли"], "togri": 1, "izoh": "Он читал, она читала, оно читало, они читали."},
        {"savol": "«Если бы у меня было время...» nimani bildiradi?", "variantlar": ["Kelasi zamon", "Shart mayli (bo'lganida edi)", "Buyruq", "Savol"], "togri": 1, "izoh": "бы + o'tgan zamon = shart mayli: «Agar vaqtim bo'lganida edi...»"},
    ],
    "talaffuz": [
        {"savol": "Urg'usiz «о» harfi odatda qanday o'qiladi?", "variantlar": ["«о» kabi", "«а» kabi", "«у» kabi", "O'qilmaydi"], "togri": 1, "izoh": "Urg'usiz «о» — «а» kabi: молоко → «malako»."},
        {"savol": "Qaysi undoshlar HAR DOIM qattiq talaffuz qilinadi?", "variantlar": ["Б, В, Г", "Ж, Ш, Ц", "Ч, Щ, Й", "Л, М, Н"], "togri": 1, "izoh": "Ж, Ш, Ц har doim qattiq: жить → «jыt'»."},
        {"savol": "«Молоко» so'zi qanday talaffuz qilinadi?", "variantlar": ["moloko", "malako", "muluko", "meleko"], "togri": 1, "izoh": "Urg'u oxirida: мо-ло-КО́ → «malako»."},
        {"savol": "So'z oxiridagi jarangli undoshlar qanday aytiladi?", "variantlar": ["Jarangli qoladi", "Jarangsiz aytiladi", "Tushib qoladi", "Cho'ziq aytiladi"], "togri": 1, "izoh": "друг → «druk», хлеб → «xlep»."},
        {"savol": "«ь» (myagkiy znak) belgisi nima vazifa bajaradi?", "variantlar": ["Unlini cho'zadi", "Undoshni yumshatadi", "Urg'uni ko'rsatadi", "Hech narsa"], "togri": 1, "izoh": "ь — oldingi undoshni yumshatadi: говорить → «т'» yumshoq."},
        {"savol": "Rus tilida urg'u (ударение) qanday?", "variantlar": ["Doim oxirgi bo'g'inda", "Doim birinchi bo'g'inda", "Erkin — istalgan bo'g'inda", "Urg'u yo'q"], "togri": 2, "izoh": "Urg'u erkin va ma'noni o'zgartiradi: за́мок (qal'a) — замо́к (qulf)."},
        {"savol": "«Хлеб» so'zi qanday aytiladi?", "variantlar": ["xleb", "xlep", "xlyob", "xlip"], "togri": 1, "izoh": "So'z oxirida б → п: «xlep»."},
        {"savol": "«Ч» harfi qanday talaffuz qilinadi?", "variantlar": ["Doim qattiq", "Doim yumshoq", "Ba'zan qattiq, ba'zan yumshoq", "O'qilmaydi"], "togri": 1, "izoh": "Ч va Щ har doim yumshoq (Ж, Ш, Ц esa har doim qattiq)."},
    ],
    "suhbat": [
        {"savol": "«Как дела?» nimani bildiradi?", "variantlar": ["Ismingiz nima?", "Ishlaring qalay?", "Qayerdansiz?", "Necha yoshdasiz?"], "togri": 1, "izoh": "Как дела? — Qalaysan? Javob: Нормально / Хорошо / Отлично."},
        {"savol": "Xayrlashayotganda «Давай!» nimani bildiradi?", "variantlar": ["Ber!", "Xayr / ko'rishguncha", "Tezroq!", "Boshla!"], "togri": 1, "izoh": "Давай ko'p ma'noli: «xayr», «kelishdik», «boshladik». Suhbat oxirida — xayr."},
        {"savol": "«Ладно» nimani bildiradi?", "variantlar": ["Yo'q", "Xo'p / mayli", "Bilmayman", "Kutib tur"], "togri": 1, "izoh": "Ладно — rozilik: «xo'p, mayli». Juda ko'p ishlatiladi."},
        {"savol": "«Короче» so'zlashuvda nimani bildiradi?", "variantlar": ["Qisqasi / xullas", "Kaltaroq", "Tezroq", "Ozroq"], "togri": 0, "izoh": "Короче — «xullas, qisqasi». Ruslar gapni shu bilan boshlashni yaxshi ko'radi."},
        {"savol": "«Чуть-чуть» nimani bildiradi?", "variantlar": ["Juda ko'p", "Ozgina", "Tez-tez", "Hech qachon"], "togri": 1, "izoh": "Чуть-чуть — ozgina. Я чуть-чуть говорю по-русски — ruschada ozgina gapiraman."},
        {"savol": "«Спасибо» ga qanday javob beriladi?", "variantlar": ["Привет", "Не за что / Пожалуйста", "Пока", "Давай"], "togri": 1, "izoh": "Не за что — arzimaydi. Пожалуйста ham bo'ladi."},
        {"savol": "«Ну» so'zi nutqda qanday vazifa bajaradi?", "variantlar": ["Savol beradi", "To'ldiruvchi so'z («xo'sh» kabi)", "Inkor qiladi", "Buyruq beradi"], "togri": 1, "izoh": "Ну — слово-паразит: «xo'sh, eee» kabi. Nutqni tabiiy qiladi."},
        {"savol": "«Блин!» undovi nimani bildiradi?", "variantlar": ["Quymoq (taom)", "Attang! / Eh! (yumshoq afsus)", "Salom", "Juda zo'r"], "togri": 1, "izoh": "So'zma-so'z «quymoq», lekin undov sifatida «attang!». Yumshoq, lekin rasmiy joyda ishlatmang."},
    ],
    "dialog": [
        {"savol": "Ko'chada notanish odamdan biror narsa so'rashdan oldin nima deysiz?", "variantlar": ["Эй, ты!", "Извините, пожалуйста...", "Иди сюда!", "Слушай меня"], "togri": 1, "izoh": "Извините, пожалуйста — muloyim murojaat. Ruslar suhbatni aynan shunday boshlaydi."},
        {"savol": "«Как пройти к метро?» nimani bildiradi?", "variantlar": ["Metro qachon ochiladi?", "Metroga qanday boriladi?", "Metro qayerda edi?", "Metro ishlayaptimi?"], "togri": 1, "izoh": "Yo'l so'rashning eng keng tarqalgan shakli. Javob: Идите прямо, потом направо — to'g'ri yuring, keyin o'ngga."},
        {"savol": "Do'konda narxni qanday so'raysiz?", "variantlar": ["Сколько это стоит?", "Где деньги?", "Что это такое?", "Дай мне это"], "togri": 0, "izoh": "Сколько (это) стоит? — bu qancha turadi? Qisqa varianti: Сколько?"},
        {"savol": "Kafeda qanday buyurtma berasiz?", "variantlar": ["Хочу есть!", "Мне, пожалуйста, кофе", "Дай кофе", "Кофе где?"], "togri": 1, "izoh": "Мне, пожалуйста, ... — eng muloyim buyurtma shakli. Oxirida: Спасибо!"},
        {"savol": "Ruslar telefon ko'targanda odatda nima deydi?", "variantlar": ["Привет, кто это?!", "Алло! / Слушаю", "Говорите быстро", "Здравствуй, товарищ"], "togri": 1, "izoh": "Алло yoki Слушаю (eshitaman) — telefondagi standart javob."},
        {"savol": "Tanishtirilgandan keyin nima deyiladi?", "variantlar": ["Очень приятно", "До свидания", "Не за что", "Ну ладно"], "togri": 0, "izoh": "Очень приятно — «tanishganimdan xursandman». To'liq: Очень приятно познакомиться."},
        {"savol": "«Как дела?» ga eng TABIIY javob qaysi?", "variantlar": ["Да", "Нормально, а у тебя?", "Спасибо", "Я студент"], "togri": 1, "izoh": "Нормально, а у тебя? — yaxshi, o'zingchi? Qarshi savol berish muloqotni tabiiy qiladi."},
        {"savol": "Taklifga xursandchilik bilan rozilik qaysi?", "variantlar": ["С удовольствием!", "Не за что", "Ничего себе", "Может быть, нет"], "togri": 0, "izoh": "С удовольствием! — jon deb! / mamnuniyat bilan."},
        {"savol": "Gapni tushunmay qolsangiz nima deysiz?", "variantlar": ["Молчи!", "Повторите, пожалуйста, я не понял", "Всё, хватит", "Неважно"], "togri": 1, "izoh": "Повторите, пожалуйста — qaytaring, iltimos. Yana: Говорите медленнее — sekinroq gapiring."},
        {"savol": "«Можно спросить?» nimani bildiradi?", "variantlar": ["So'rasam maylimi?", "Sotib olsam bo'ladimi?", "Ketsam maylimi?", "Kirsam maylimi?"], "togri": 0, "izoh": "Можно...? — ruxsat so'rashning universal shakli: Можно войти? — kirsam maylimi?"},
        {"savol": "Kechikkan odam «Извини, пробки!» desa, nima demoqchi?", "variantlar": ["Ishim ko'p edi", "Yo'lda tirbandlik edi", "Uxlab qoldim", "Unutibman"], "togri": 1, "izoh": "Пробка — so'zma-so'z «tiqin», so'zlashuvda — yo'l tirbandligi. Eng ko'p eshitiladigan bahona 😄"},
        {"savol": "Do'stlar bilan norasmiy xayrlashuv qaysi?", "variantlar": ["До свидания, господин", "Пока! Увидимся!", "Прощайте навсегда", "Всего доброго, коллеги"], "togri": 1, "izoh": "Пока — xayr (do'stona), Увидимся — ko'rishamiz. Rasmiy: До свидания."},
        {"savol": "«Что ты имеешь в виду?» nimani bildiradi?", "variantlar": ["Nimani ko'ryapsan?", "Nima demoqchisan?", "Qayerga qarayapsan?", "Nima xohlaysan?"], "togri": 1, "izoh": "Иметь в виду — nazarda tutmoq. Suhbatda aniqlik kiritish uchun juda kerak ibora."},
        {"savol": "Mehmonga kelgan odamga ruslar nima deydi?", "variantlar": ["Проходите, садитесь!", "Стой там!", "Зачем пришёл?", "Плати сначала"], "togri": 0, "izoh": "Проходите, садитесь — kiring, o'tiring. Yana: Чувствуй себя как дома — o'z uyingdek his qil."},
    ],
    "anime": [
        {"savol": "«Я тебя убью!» nimani bildiradi?", "variantlar": ["Seni sevaman!", "Seni o'ldiraman!", "Seni kutaman!", "Seni ko'raman!"], "togri": 1, "izoh": "Anime'dagi eng mashhur tahdid iborasi. Убить — o'ldirmoq."},
        {"savol": "«Не сдавайся!» nimani bildiradi?", "variantlar": ["Taslim bo'lma!", "Gapirma!", "Kelma!", "Qo'rqma!"], "togri": 0, "izoh": "Сдаваться — taslim bo'lmoq. Anime qahramonlarining sevimli gapi!"},
        {"savol": "«Враг» so'zining ma'nosi nima?", "variantlar": ["Do'st", "Dushman", "Qahramon", "Ustoz"], "togri": 1, "izoh": "Враг — dushman. Враги — dushmanlar."},
        {"savol": "«Держись!» nimani bildiradi?", "variantlar": ["Yugur!", "Chida! / Mahkam tur!", "Tashla!", "Qara!"], "togri": 1, "izoh": "Держись! — chida, bardosh ber! Jangda yaralangan do'stga aytiladi."},
        {"savol": "«Судьба» so'zining ma'nosi nima?", "variantlar": ["Sud", "Taqdir", "Kuch", "Baxt"], "togri": 1, "izoh": "Судьба — taqdir. Это моя судьба — bu mening taqdirim."},
        {"savol": "«Заткнись!» nimani bildiradi?", "variantlar": ["Yopiq!", "Ovozingni o'chir!", "Eshikni yop!", "To'xta!"], "togri": 1, "izoh": "Qo'pol «jim bo'l». Anime'da juda ko'p, lekin real hayotda ehtiyot bo'ling."},
        {"savol": "Uyga kelganda «Я дома!» deyiladi. Bu nima?", "variantlar": ["Men keldim!", "Men ketdim!", "Uy qani?", "Men uyman!"], "togri": 0, "izoh": "Я дома! — «tadaima» ning ruscha tarjimasi. Javobi: С возвращением!"},
        {"savol": "«С возвращением!» nimani bildiradi?", "variantlar": ["Xayr!", "Xush kelibsan! (qaytganingga)", "Qaytib kel!", "Tez bo'l!"], "togri": 1, "izoh": "«Okaeri» ning ruscha tarjimasi — qaytib kelgan odamga aytiladi."},
        {"savol": "Anime'da «учитель» deb kimga murojaat qilinadi?", "variantlar": ["Ustoz (sensei)", "Ota", "Aka", "Do'st"], "togri": 0, "izoh": "Учитель — sensei so'zining ruscha dublyajdagi tarjimasi."},
        {"savol": "«Ты в порядке?» nimani bildiradi?", "variantlar": ["Tartibga sol!", "Yaxshimisan?", "Qatorda tur!", "Sen kimsan?"], "togri": 1, "izoh": "So'zma-so'z «tartibdamisan?» — ya'ni «yaxshimisan, tinchmisan?». Jangdan keyin doim eshitasiz."},
        {"savol": "«Меч» so'zining ma'nosi nima?", "variantlar": ["O'q", "Qilich", "Qalqon", "Nayza"], "togri": 1, "izoh": "Меч — qilich (katana). Оружие — qurol."},
        {"savol": "«Ничего себе!» nimani bildiradi?", "variantlar": ["O'zimga hech narsa", "Voy-bo'y! / Qoyil!", "Menga baribir", "Hech qachon"], "togri": 1, "izoh": "Hayrat undovi: «voy-bo'y, zo'r-ku!». So'zma-so'z tarjima qilinmaydi."},
        {"savol": "«Это ещё не конец!» nimani bildiradi?", "variantlar": ["Bu boshlanishi!", "Bu hali oxiri emas!", "Bu oxirgisi!", "Tamom bo'ldi!"], "togri": 1, "izoh": "Конец — oxiri. Mag'lub bo'layotgan qahramonning klassik gapi!"},
        {"savol": "«Братик» qanday ohangda ishlatiladi?", "variantlar": ["Qo'pol", "Erkalash: «ukajon/akajon» (onii-chan)", "Rasmiy", "G'azab bilan"], "togri": 1, "izoh": "-ик qo'shimchasi erkalash: брат → братик. Onii-chan odatda shunday tarjima qilinadi."},
        {"savol": "«Осторожно!» nimani bildiradi?", "variantlar": ["Tez bo'l!", "Ehtiyot bo'l!", "Orqaga qara!", "Sekinroq!"], "togri": 1, "izoh": "Xavf oldidan ogohlantirish. Ko'pincha: Осторожно, сзади! — ehtiyot bo'l, orqangda!"},
        {"savol": "«Слёзы» so'zining ma'nosi nima?", "variantlar": ["So'zlar", "Ko'z yoshlari", "Orzular", "Xotiralar"], "togri": 1, "izoh": "Слёзы — ko'z yoshlari. Не плачь — yig'lama."},
    ],
}


# ⛩ Anime lug'ati — botdagi «📕 Anime lug'ati» tugmasi shu ro'yxatni ko'rsatadi.
# Yangi so'z qo'shish: kerakli bo'limning "sozlar" ro'yxatiga ("Ruscha", "Tarjima") juftligini qo'shing.
ANIME_LUGAT = {
    "undov": {
        "nom": "😱 Undov va his-tuyg'ular",
        "sozlar": [
            ("Что?!", "Nima?!"),
            ("Чёрт!", "Jin ursin!"),
            ("Блин!", "Attang!"),
            ("Ничего себе!", "Voy-bo'y! / Qoyil!"),
            ("Не может быть!", "Bo'lishi mumkin emas!"),
            ("Серьёзно?", "Jiddiymi?"),
            ("Правда?", "Rostdanmi?"),
            ("Неужели?!", "Nahotki?!"),
            ("Наконец-то!", "Nihoyat!"),
            ("Невероятно!", "Aql bovar qilmaydi!"),
            ("Как ты смеешь?!", "Qanday jur'at etding?!"),
            ("Заткнись!", "Ovozingni o'chir!"),
            ("Отстань!", "Tinch qo'y meni!"),
            ("Дурак / Идиот", "Ahmoq / Tentak (baka)"),
            ("Молодец!", "Barakalla!"),
            ("Ура!", "Ura!"),
            ("Хватит!", "Bo'ldi, yetar!"),
            ("Успокойся", "Tinchlan"),
        ],
    },
    "jang": {
        "nom": "⚔️ Jang va kuch",
        "sozlar": [
            ("Сила", "Kuch"),
            ("Враг", "Dushman"),
            ("Битва / Бой", "Jang"),
            ("Атака", "Hujum"),
            ("Защита", "Himoya"),
            ("Победа", "G'alaba"),
            ("Поражение", "Mag'lubiyat"),
            ("Меч", "Qilich (katana)"),
            ("Оружие", "Qurol"),
            ("Магия", "Sehr"),
            ("Заклинание", "Afsun"),
            ("Демон", "Jin / dev"),
            ("Дух", "Ruh"),
            ("Герой", "Qahramon"),
            ("Злодей", "Yovuz qahramon"),
            ("Смерть", "O'lim"),
            ("Кровь", "Qon"),
            ("Рана", "Jarohat"),
            ("Сильный / Слабый", "Kuchli / Kuchsiz"),
            ("Опасно!", "Xavfli!"),
        ],
    },
    "buyruq": {
        "nom": "🏃 Buyruq va harakat",
        "sozlar": [
            ("Стой!", "To'xta!"),
            ("Подожди!", "Kutib tur!"),
            ("Беги!", "Qoch! / Yugur!"),
            ("Быстрее!", "Tezroq!"),
            ("Вперёд!", "Olg'a!"),
            ("Назад!", "Orqaga!"),
            ("Держись!", "Chida! / Mahkam tur!"),
            ("Осторожно!", "Ehtiyot bo'l!"),
            ("Помогите!", "Yordam beringlar!"),
            ("Спаси меня!", "Meni qutqar!"),
            ("Не сдавайся!", "Taslim bo'lma!"),
            ("Вставай!", "Tur o'rningdan!"),
            ("Смотри!", "Qara!"),
            ("Слушай!", "Eshit!"),
            ("Иди сюда!", "Bu yoqqa kel!"),
            ("Уходи!", "Ket!"),
            ("Не двигайся!", "Qimirlama!"),
            ("Прячься!", "Yashirin!"),
        ],
    },
    "qalb": {
        "nom": "❤️ Munosabat va qalb",
        "sozlar": [
            ("Друг", "Do'st"),
            ("Лучший друг", "Eng yaqin do'st"),
            ("Брат / Братик", "Aka-uka / Ukajon (onii-chan)"),
            ("Сестра / Сестрёнка", "Opa-singil / Singiljon"),
            ("Учитель", "Ustoz (sensei)"),
            ("Старший", "Katta (senpai ma'nosida)"),
            ("Любовь", "Sevgi"),
            ("Сердце", "Yurak"),
            ("Душа", "Qalb / ruh"),
            ("Судьба", "Taqdir"),
            ("Мечта", "Orzu"),
            ("Надежда", "Umid"),
            ("Обещание", "Va'da"),
            ("Доверие", "Ishonch"),
            ("Воспоминания", "Xotiralar"),
            ("Слёзы", "Ko'z yoshlari"),
            ("Улыбка", "Tabassum"),
            ("Одиночество", "Yolg'izlik"),
        ],
    },
    "ibora": {
        "nom": "💯 Mashhur anime iboralari",
        "sozlar": [
            ("Я тебя убью!", "Seni o'ldiraman!"),
            ("Я не позволю!", "Yo'l qo'ymayman!"),
            ("Я тебя защищу!", "Seni himoya qilaman!"),
            ("Это невозможно!", "Bu mumkin emas!"),
            ("Что происходит?", "Nima bo'lyapti?"),
            ("Кто ты такой?", "O'zi kimsan?"),
            ("Ты в порядке?", "Yaxshimisan?"),
            ("Всё будет хорошо", "Hammasi yaxshi bo'ladi"),
            ("Верь мне", "Menga ishon"),
            ("Обещаю", "Va'da beraman"),
            ("Прости меня", "Meni kechir"),
            ("Прощай", "Alvido"),
            ("Слишком поздно", "Juda kech"),
            ("Это ещё не конец!", "Bu hali oxiri emas!"),
            ("Никогда не сдамся!", "Hech qachon taslim bo'lmayman!"),
            ("Я стану сильнее!", "Kuchliroq bo'laman!"),
            ("Ради друзей", "Do'stlar uchun"),
            ("Покажи, на что ты способен!", "Nimaga qodirligingni ko'rsat!"),
        ],
    },
    "kundalik": {
        "nom": "🍜 Kundalik anime hayoti",
        "sozlar": [
            ("Школа", "Maktab"),
            ("Класс", "Sinf"),
            ("Урок", "Dars"),
            ("Экзамен", "Imtihon"),
            ("Клуб", "To'garak / klub"),
            ("Обед", "Tushlik"),
            ("Вкусно!", "Mazali!"),
            ("Я голоден", "Qornim och"),
            ("Доброе утро", "Xayrli tong"),
            ("Спокойной ночи", "Xayrli tun"),
            ("Добро пожаловать", "Xush kelibsiz"),
            ("Я дома!", "Men keldim! (tadaima)"),
            ("С возвращением!", "Xush kelibsan! (okaeri)"),
            ("Извини за опоздание", "Kechikkanim uchun uzr"),
            ("Пойдём вместе", "Birga boramiz"),
            ("Увидимся завтра", "Ertaga ko'rishamiz"),
            ("Удачи!", "Omad!"),
            ("Приятного аппетита", "Yoqimli ishtaha"),
        ],
    },
    "nodir": {
        "nom": "🧙 Nodir va qadimiy so'zlar",
        "sozlar": [
            ("Владыка", "Hukmdor / oliy hazrat"),
            ("Господин / Госпожа", "Janob / Xonim"),
            ("Клинок", "Tig' (qilich tig'i)"),
            ("Возмездие", "Qasos / jazo (taqdir jazosi)"),
            ("Месть", "Qasos"),
            ("Проклятие", "La'nat"),
            ("Пророчество", "Bashorat"),
            ("Древний", "Qadimiy"),
            ("Бессмертный", "O'lmas / mangu tirik"),
            ("Жертва", "Qurbon"),
            ("Клятва", "Qasamyod"),
            ("Предатель", "Xoin / sotqin"),
            ("Гибель", "Halokat / o'lim (yuksak uslub)"),
            ("Воскрешение", "Tirilish / qayta jonlanish"),
            ("Тьма", "Zulmat / qorong'ulik"),
            ("Свет", "Nur / yorug'lik"),
            ("Вечность", "Abadiyat"),
            ("Небеса", "Samovot / osmonlar"),
            ("Преисподняя", "Do'zax (qadimiy so'z)"),
            ("Сущность", "Mohiyat / mavjudot"),
        ],
    },
    "qiyin": {
        "nom": "🎓 Juda qiyin so'zlar (C1)",
        "sozlar": [
            ("Предназначение", "Taqdirda yozilgan vazifa"),
            ("Самопожертвование", "O'zini qurbon qilish"),
            ("Справедливость", "Adolat"),
            ("Предательство", "Xiyonat"),
            ("Искупление", "Gunohni yuvish / poklanish"),
            ("Возрождение", "Qayta tug'ilish (isekai!)"),
            ("Отчаяние", "Umidsizlik / tushkunlik"),
            ("Решимость", "Qat'iyat"),
            ("Неизбежность", "Muqarrarlik"),
            ("Превосходство", "Ustunlik"),
            ("Могущество", "Qudrat"),
            ("Уязвимость", "Zaif nuqta / himoyasizlik"),
            ("Безысходность", "Chorasizlik"),
            ("Высокомерие", "Takabburlik / kibr"),
            ("Милосердие", "Rahm-shafqat"),
            ("Ненависть", "Nafrat"),
            ("Сожаление", "Afsus / pushaymonlik"),
            ("Достоинство", "Qadr-qimmat / or-nomus"),
            ("Осознание", "Anglash / anglab yetish"),
            ("Стремление", "Intilish"),
        ],
    },
    "kam": {
        "nom": "🗿 Kam ishlatiladigan iboralar",
        "sozlar": [
            ("Да будет так!", "Shunday bo'lsin!"),
            ("Как пожелаешь", "Xohishingcha bo'lsin"),
            ("Не смей!", "Yurak qilma! / Aslo qilma!"),
            ("Прочь с дороги!", "Yo'ldan qoch!"),
            ("Ты заплатишь за это!", "Buning uchun javob berasan!"),
            ("Настал твой час", "Sening soating yetib keldi"),
            ("Во что бы то ни стало", "Nima bo'lsa ham / har qanday yo'l bilan"),
            ("Рано или поздно", "Ertami-kechmi"),
            ("Ни за что на свете!", "Hech qachon, aslo!"),
            ("Будь по-твоему", "Sen aytganday bo'lsin"),
            ("Клянусь жизнью", "Hayotim bilan qasam ichaman"),
            ("Это лишь начало", "Bu faqat boshlanishi"),
            ("Ты не оставил мне выбора", "Menga boshqa yo'l qoldirmading"),
            ("Время пришло", "Vaqt-soati keldi"),
            ("Именно так", "Xuddi shunday / aynan"),
            ("Каким-то образом", "Qandaydir yo'l bilan"),
            ("Несмотря ни на что", "Hech narsaga qaramay"),
            ("Отныне и навсегда", "Bundan buyon va abadiy"),
            ("Считай, что тебе повезло", "Omading bor ekan deb hisobla"),
            ("Этому не бывать!", "Bunga aslo yo'l qo'ymayman!"),
        ],
    },
}
